  // Error messages from core and adjacent classes
  SCannotReleaseInstance_rst = 'Cannot release instance ''%s''';
  SEnumItemNotFound_rst = 'Enumeration ''%s'' not found';
  SInvalidIdentifier_rst = 'Invalid identifier ''%s''';
  SInvalidInterfaceTypecast_rst = 'Invalid interface typecast';
  SInvalidLogon_rst = 'Invalid username or password';
  SMethodNotFound_rst = 'Method ''%s'' not found';
  SNoLoggedUser_rst = 'No user logged in';
  SPasswordsDontMatch_rst = 'Passwords don''t match';
  SPropertyIsReadOnly_rst = 'The property ''%s.%s'' is read only';
  SPropertyNotFound_rst = 'Property ''%s.%s'' not found';
  SServiceNotFound_rst = 'Service ''%s'' not found';
  SStringLengthOutOfBounds_rst = 'String length out of bounds';
  STokenExpected_rst = '''%s'' was expected, but ''%s'' was found';
  STokenLengthOutOfBounds_rst = 'Token length out of bounds';
  SUnassignedAppManager_rst = 'App manager was not assigned';
  SUnassignedServiceType_rst = 'No service ''%s'' is assigned or registered';
  SUnexpectedEof_rst = 'Unexpected end of file';
  SUnsupportedFeature_rst = 'Unsupported feature ''%s''';
  SUnsupportedVariantType_rst = 'Unsupported variant type';

  // Error messages from the Data Type (Subject) framework
  SAttributeAccessError_rst = 'Cannot access the attribute %s(''%s'') as ''%s''';
  SAttributeConversionError_rst = 'Attribute value conversion error %s(''%s''):' + SPressLineBreak + '"%s"';
  SAttributeIsNotItem_rst = 'Attribute %s(''%s'') is not a Part or Reference';
  SAttributeIsNotValue_rst = 'Attribute %s(''%s'') is not a Value';
  SAttributeNotFound_rst = 'Attribute %s(''%s'') not found';
  SAttributeTypeNotFound_rst = 'Attribute ''%s'' not found';
  SCannotRecursivelyCreateMetadatas_rst = 'Cannot recursively create metadatas';
  SClassNotFound_rst = 'Class ''%s'' not found';
  SEnumMetadataNotFound_rst = 'Enumeration metadata ''%s'' not found';
  SEnumOutOfBounds_rst = 'Enumeration ''%s'' is out of bounds (%d)';
  SInstanceAlreadyOwned_rst = 'The instance %s(''%s'') already has an owner';
  SInstanceNotFound_rst = 'Instance not found: %s(''%s'')';
  SInvalidAttributeClass_rst = 'Attribute %s(''%s'') requires objects of class ''%s''';
  SInvalidAttributeName_rst = 'Invalid attribute name (''%s'')';
  SInvalidAttributeValue_rst = 'Value ''%s'' is invalid for %s(''%s'')';
  SInvalidClassInheritance_rst = 'Class ''%s'' is not a descendant of ''%s''';
  SMetadataNotFound_rst = 'Metadata ''%s'' not found';
  SMetadataParseError_rst = 'Metadata parse error: "(%d,%d) %s"' + SPressLineBreak + '"%s"';
  SNoReferenceOrDataAccess_rst = 'Reference or DAO does not exist';
  SParseFormulaError_rst = 'Error parsing formula:' + SPressLineBreak + '%s' + SPressLineBreak + '%s';
  SPathReferencesNil_rst = 'The path %s(''%s'') has attribute(s) with nil reference(s)';
  SSingletonClassNotFound_rst = 'Singleton class ''%s'' not found';
  SStringOverflow_rst = 'String overflow: %s(''%s'')';
  SUnsupportedAttribute_rst = 'Unsupported attribute %s(''%s'')';
  SUnsupportedAttributeType_rst = 'Unsupported attribute type ''%s''';
  SUnsupportedGraphicFormat_rst = 'Unsupported graphic format';

  // Error messages from the MVP framework
  SAmbiguousClass_rst = 'Ambiguous choice between classes ''%s'' and ''%s''';
  SColumnDataParseError_rst = 'Column data parse error %s(''%s''): "%s"';
  SComponentIsNotAControl_rst = 'Component %s(''%s'') is not a control';
  SComponentNotFound_rst = 'Component %s(''%s'') not found';
  SDisplayNamesAlreadyAssigned_rst = 'DisplayNames is already assigned';
  SMaxItemCountReached_rst = '%d items were returned, the limit is %d';
  SUnassignedAttributeType_rst = 'Unassigned attribute type %s(''%s'')';
  SUnassignedItemObjectClass_rst = 'Unassigned business class Query item ''%s''';
  SUnassignedMainForm_rst = 'Unassigned main form';
  SUnassignedModel_rst = 'Unassigned Model';
  SUnassignedPresenterBO_rst = 'Class ''%s'' does not have business object';
  SUnassignedPresenterForm_rst = 'Class ''%s'' does not have form';
  SUnassignedPresenterParent_rst = 'Class ''%s'' does not have a parent';
  SUnassignedSubject_rst = 'Unassigned Subject';
  SUnassignedWidgetManager_rst = 'Unassigned widget manager';
  SUnexpectedMVPClassParam_rst = 'MVP class ''%s'' has unexpected parameters';
  SUnsupportedComponent_rst = 'Unsupported component ''%s''';
  SUnsupportedControl_rst = 'Unsupported control %s(''%s'')';
  SUnsupportedDisplayNames_rst = 'Unsupported DisplayNames for attribute %s(''%s.%s'')';
  SUnsupportedModel_rst = 'Model %s is not supported by ''%s''';
  SUnsupportedObject_rst = 'No class %s supports objects ''%s''';
  SUnsupportedSubject_rst = '''%s'' metaclass does not support ''%s'' subject';
  SViewAccessError_rst = 'Cannot access the view %s(''%s'') as ''%s''';
  SWidgetManagerAlreadyAssigned_rst = 'Widget manager was already assigned';

  // Error messages from the OPF framework
  SAttributeReferencesOwnedClass_rst = '%s(%s) references ''%s'' which is owned by ''%s''';
  SCannotChangeOPFBroker_rst = 'Cannot change the data broker';
  SCannotStoreOrphanObject_rst = 'Cannot store orphan object';
  SCannotUseAggregateFunctionHere_rst = 'Cannot use aggregate function here';
  SClassIsNotPersistent_rst = 'Class ''%s'' is not persistent';
  SDatabaseIdentifierTooLong_rst = 'The identifier is too long' + SPressLineBreak + 'and will cause an error in the database:';
  SFieldNotFound_rst = 'Field ''%s'' not found';
  SObjectChangedError_rst = 'The object %s(''%s'') was modified in another session';
  STargetClassIsNotPersistent_rst = '%s(%s) references ''%s'' which is not persistent';
  SUnassignedPersistenceService_rst = 'Unassigned or non-PressObjects persistence service';
  SUnsupportedConnector_rst = 'Unsupported connector ''%s''';
  SUnsupportedFieldType_rst = 'Unsupported field type ''%s''';

  // Error messages from brokers
  SUnassignedPersistenceConnector_rst = 'Unassigned persistence connector';

  // Messages for visual components
  SConnectionManagerCaption_rst = 'Connector';

  // Messages for Commands
  SPressTodayCommand_rst = 'Today';
  SPressLoadPictureCommand_rst = 'Load Picture';
  SPressRemovePictureCommand_rst = 'Remove Picture';
  SPressIncludeObjectCommand_rst = 'Add new item';
  SPressAddItemCommand_rst = 'Add item';
  SPressSelectItemCommand_rst = 'Select items';
  SPressEditItemCommand_rst = 'Edit item';
  SPressRemoveItemCommand_rst = 'Delete item';
  SPressRefreshCommand_rst = 'Refresh';
  SPressSaveFormCommand_rst = 'Save';
  SPressCancelFormCommand_rst = 'Cancel';
  SPressCloseFormCommand_rst = 'Close';
  SPressExecuteQueryCommand_rst = 'Execute';
  SPressAssignSelectionQueryCommand_rst = 'Filter';
  SPressSelectAllCommand_rst = 'Select All';
  SPressSelectNoneCommand_rst = 'Deselect All';
  SPressSelectCurrentCommand_rst = 'Select/Deselect Current';
  SPressSelectInvertCommand_rst = 'Invert Selection';
  SPressSortByCommand_rst = 'Sort by ''%s''';
  SPressManageReportCommand_rst = 'Manage Report';

  // Partial translations for parsers or another error messages
  SPressAttributeNameMsg_rst = 'attribute name';
  SPressBooleanValueMsg_rst = 'Boolean value';
  SPressClassNameMsg_rst = 'class name';
  SPressExpressionMsg_rst = 'Expression';
  SPressEofMsg_rst = 'End of file';
  SPressFunctionMsg_rst = 'Function';
  SPressIdentifierMsg_rst = 'Identifier';
  SPressIntegerValueMsg_rst = 'Integer';
  SPressLineBreakMsg_rst = 'Line break';
  SPressNumberValueMsg_rst = 'Number';
  SPressPropertyNameMsg_rst = 'property name';
  SPressReportErrorMsg_rst = ' ##Error## ';
  SPressStringDelimiterMsg_rst = 'String delimiter';
  SPressStringValueMsg_rst = 'String';

  // Messages for user access
  SPressNoAccess_rst = 'No access';
  SPressReadOnlyAccess_rst = 'Read-only access';
  SPressReadWriteAccess_rst = 'Full access';

  // Messages for dialog box
  SPressCancelChangesDialog_rst = 'Cancel changes?';
  SPressConfirmRemoveOneItemDialog_rst = 'One item selected. Confirm delete?';
  SPressConfirmRemoveItemsDialog_rst = '%d items selected. Confirm delete?';
  SPressSaveChangesDialog_rst = 'Save changes?';
