  // Error messages from core and adjacent classes
  SCannotReleaseInstance_rst = 'Não é possível liberar a instância ''%s''';
  SEnumItemNotFound_rst = 'Enumeration ''%s'' não encontrado';
  SInvalidIdentifier_rst = 'Identificador inválido ''%s''';
  SInvalidInterfaceTypecast_rst = 'Typecast de interface inválido';
  SInvalidLogon_rst = 'Nome de usuário ou senha incorretos';
  SMethodNotFound_rst = 'Método ''%s'' não encontrado';
  SNoLoggedUser_rst = 'Não existe usuário logado';
  SPasswordsDontMatch_rst = 'As senhas não são iguais';
  SPropertyIsReadOnly_rst = 'A propriedade ''%s.%s'' é somente leitura';
  SPropertyNotFound_rst = 'A propriedade ''%s.%s'' não foi encontrada';
  SServiceNotFound_rst = 'Serviço ''%s'' não encontrado';
  SStringLengthOutOfBounds_rst = 'String muito grande';
  STokenExpected_rst = '''%s'' esperado, mas ''%s'' foi encontrado';
  STokenLengthOutOfBounds_rst = 'Token muito grande';
  SUnassignedAppManager_rst = 'Gerenciador de aplicação não foi associado';
  SUnassignedServiceType_rst = 'Nenhum serviço ''%s'' foi associado ou registrado';
  SUnexpectedEof_rst = 'Final de arquivo inesperado';
  SUnsupportedFeature_rst = 'Feature ''%s'' não é suportada';
  SUnsupportedVariantType_rst = 'Tipo variant não suportado';

  // Error messages from the Data Type (Subject) framework
  SAttributeAccessError_rst = 'Não é possível acessar o atributo %s(''%s'') como ''%s''';
  SAttributeConversionError_rst = 'Erro ao converter valor para o atributo %s(''%s''):' + SPressLineBreak + '"%s"';
  SAttributeIsNotItem_rst = 'O atributo %s(''%s'') não é Part ou Reference';
  SAttributeIsNotValue_rst = 'O atributo %s(''%s'') não é Value';
  SAttributeNotFound_rst = 'O atributo %s(''%s'') não foi encontrado';
  SAttributeTypeNotFound_rst = 'O atributo ''%s'' não foi encontrado';
  SCannotRecursivelyCreateMetadatas_rst = 'Não é possível criar metadatas recursivamente';
  SClassNotFound_rst = 'Classe ''%s'' não encontrada';
  SEnumMetadataNotFound_rst = 'Enumeration metadata ''%s'' não encontrado';
  SEnumOutOfBounds_rst = 'Enumeration ''%s'' fora do limite (%d)';
  SInstanceAlreadyOwned_rst = 'O objeto %s(''%s'') já possui proprietário';
  SInstanceNotFound_rst = 'Instância não encontrada: %s(''%s'')';
  SInvalidAttributeClass_rst = 'O atributo %s(''%s'') requer objetos da classe ''%s''';
  SInvalidAttributeName_rst = 'Nome inválido para um atributo (''%s'')';
  SInvalidAttributeValue_rst = 'Valor ''%s'' inválido para %s(''%s'')';
  SInvalidClassInheritance_rst = 'Classe ''%s'' não é descendente de ''%s''';
  SMetadataNotFound_rst = 'Metadata ''%s'' não encontrado';
  SMetadataParseError_rst = 'Erro ao interpretar metadata: "(%d,%d) %s"' + SPressLineBreak + '"%s"';
  SNoReferenceOrDataAccess_rst = 'Não existe referência ou DAO';
  SParseFormulaError_rst = 'Erro ao interpretar fórmula:' + SPressLineBreak + '%s' + SPressLineBreak + '%s';
  SPathReferencesNil_rst = 'O caminho %s(''%s'') possui atributo(s) Reference apontando para nil';
  SSingletonClassNotFound_rst = 'Classe Singleton ''%s'' não encontrada';
  SStringOverflow_rst = 'String overflow: %s(''%s'')';
  SUnsupportedAttribute_rst = 'O atributo %s(''%s'') não é suportado';
  SUnsupportedAttributeType_rst = 'O tipo de atributo ''%s'' não é suportado';
  SUnsupportedGraphicFormat_rst = 'Formato de arquivo gráfico não suportado';

  // Error messages from the MVP framework
  SAmbiguousClass_rst = 'Ambiguidade entre as classes ''%s'' e ''%s''';
  SColumnDataParseError_rst = 'Erro ao interpretar dados da coluna %s(''%s''): "%s"';
  SComponentIsNotAControl_rst = 'O componente %s(''%s'') não é um controle';
  SComponentNotFound_rst = 'O componente %s(''%s'') não foi encontrado';
  SDisplayNamesAlreadyAssigned_rst = 'DisplayNames já foi associado';
  SMaxItemCountReached_rst = 'A consulta retornou %d itens, o limite é %d';
  SUnassignedAttributeType_rst = 'Tipo de atributo não associado para %s(''%s'')';
  SUnassignedItemObjectClass_rst = 'Classe de negócio dos itens da Query ''%s'' não está associado';
  SUnassignedMainForm_rst = 'Formulário principal não está associado';
  SUnassignedModel_rst = 'Model não está associado';
  SUnassignedPresenterBO_rst = 'A classe ''%s'' não possui objeto de negócio';
  SUnassignedPresenterForm_rst = 'A classe ''%s'' não possui form';
  SUnassignedPresenterParent_rst = 'A classe ''%s'' não possui parent';
  SUnassignedSubject_rst = 'Subject não foi associado';
  SUnassignedWidgetManager_rst = 'Nenhum widget manager foi registrado';
  SUnexpectedMVPClassParam_rst = 'Classe MVP ''%s'' inicializada com parâmetros inesperados';
  SUnsupportedComponent_rst = 'O componente ''%s'' não é suportado';
  SUnsupportedControl_rst = 'O controle %s(''%s'') não é suportado';
  SUnsupportedDisplayNames_rst = 'DisplayNames não é suportado para o atributo %s(''%s.%s'')';
  SUnsupportedModel_rst = 'Model ''%s'' não é suportado por ''%s''';
  SUnsupportedObject_rst = 'Nenhuma classe ''%s'' suporta objetos ''%s''';
  SUnsupportedSubject_rst = 'A metaclasse ''%s'' não suporta subject ''%s''';
  SViewAccessError_rst = 'Não é possível acessar a view %s(''%s'') como ''%s''';
  SWidgetManagerAlreadyAssigned_rst = 'Widget manager já foi associado';

  // Error messages from the OPF framework
  SAttributeReferencesOwnedClass_rst = '%s(%s) faz referência a ''%s'' que pertence a ''%s''';
  SCannotChangeOPFBroker_rst = 'Não é possível alterar o Broker de acesso a dados';
  SCannotStoreOrphanObject_rst = 'Não é possível gravar objetos órfãos';
  SCannotUseAggregateFunctionHere_rst = 'Não é possível utilizar função de agregação aqui';
  SClassIsNotPersistent_rst = 'Classe ''%s'' não é persistente';
  SDatabaseIdentifierTooLong_rst = 'Estes identificadores são muito grandes' + SPressLineBreak + 'e causarão erro no banco de dados:';
  SFieldNotFound_rst = 'Campo ''%s'' não foi encontrado';
  SObjectChangedError_rst = 'O objeto %s(''%s'') foi alterado em outra sessão';
  STargetClassIsNotPersistent_rst = '%s(%s) aponta para ''%s'' que não é persistente';
  SUnassignedPersistenceService_rst = 'Serviço de persistência não foi associado ou não é do PressObjects';
  SUnsupportedConnector_rst = 'O conector ''%s'' não é suportado';
  SUnsupportedFieldType_rst = 'O tipo de campo ''%s'' não é suportado';

  // Error messages from brokers
  SUnassignedPersistenceConnector_rst = 'Conector de persistência não foi associado';

  // Messages for visual components
  SConnectionManagerCaption_rst = 'Conector';

  // Messages for Commands
  SPressTodayCommand_rst = 'Hoje';
  SPressLoadPictureCommand_rst = 'Carregar figura';
  SPressRemovePictureCommand_rst = 'Remover figura';
  SPressIncludeObjectCommand_rst = 'Cadastrar novo item';
  SPressAddItemCommand_rst = 'Adicionar item';
  SPressInsertItemCommand_rst = 'Inserir item';
  SPressSelectItemCommand_rst = 'Selecionar itens';
  SPressEditItemCommand_rst = 'Alterar item';
  SPressRemoveItemCommand_rst = 'Remover item';
  SPressRefreshCommand_rst = 'Atualizar';
  SPressSaveFormCommand_rst = 'Salvar';
  SPressCancelFormCommand_rst = 'Cancelar';
  SPressCloseFormCommand_rst = 'Fechar';
  SPressExecuteQueryCommand_rst = 'Executar';
  SPressAssignSelectionQueryCommand_rst = 'Selecionar';
  SPressSelectAllCommand_rst = 'Selecionar tudo';
  SPressSelectNoneCommand_rst = 'Remover seleção';
  SPressSelectCurrentCommand_rst = 'Selecionar/remover atual';
  SPressSelectInvertCommand_rst = 'Inverter seleção';
  SPressSortByCommand_rst = 'Ordernar por ''%s''';
  SPressManageReportCommand_rst = 'Gerenciar Relatório';

  // Partial translations for parsers or another error messages
  SPressAttributeNameMsg_rst = 'nome de atributo';
  SPressBooleanValueMsg_rst = 'Valor lógico';
  SPressClassNameMsg_rst = 'nome de classe';
  SPressExpressionMsg_rst = 'Expressão';
  SPressEofMsg_rst = 'Final de arquivo';
  SPressFunctionMsg_rst = 'Função';
  SPressIdentifierMsg_rst = 'Identificador';
  SPressIntegerValueMsg_rst = 'Inteiro';
  SPressLineBreakMsg_rst = 'Quebra de linha';
  SPressNumberValueMsg_rst = 'Número';
  SPressPropertyNameMsg_rst = 'nome de propriedade';
  SPressReportErrorMsg_rst = ' ##Erro## ';
  SPressStringDelimiterMsg_rst = 'Delimitador de string';
  SPressStringValueMsg_rst = 'String';

  // Messages for user access
  SPressNoAccess_rst = 'Sem acesso';
  SPressReadOnlyAccess_rst = 'Apenas leitura';
  SPressReadWriteAccess_rst = 'Acesso completo';

  // Messages for dialog box
  SPressCancelChangesDialog_rst = 'Cancelar alterações?';
  SPressConfirmRemoveOneItemDialog_rst = 'Um item selecionado. Confirma remoção?';
  SPressConfirmRemoveItemsDialog_rst = '%d itens selecionados. Confirma remoção?';
  SPressSaveChangesDialog_rst = 'Gravar alterações?';
