  // Error messages from core and adjacent classes
  SCannotReleaseInstance := SCannotReleaseInstance_rst;
  SEnumItemNotFound := SEnumItemNotFound_rst;
  SInvalidLogon := SInvalidLogon_rst;
  SNoLoggedUser := SNoLoggedUser_rst;
  SPasswordsDontMatch := SPasswordsDontMatch_rst;
  SPropertyIsReadOnly := SPropertyIsReadOnly_rst;
  SPropertyNotFound := SPropertyNotFound_rst;
  SServiceNotFound := SServiceNotFound_rst;
  SStringLengthOutOfBounds := SStringLengthOutOfBounds_rst;
  STokenExpected := STokenExpected_rst;
  STokenLengthOutOfBounds := STokenLengthOutOfBounds_rst;
  SUnassignedServiceType := SUnassignedServiceType_rst;
  SUnexpectedEof := SUnexpectedEof_rst;
  SUnsupportedFeature := SUnsupportedFeature_rst;

  // Error messages from the Data Type (Subject) framework
  SAttributeAccessError := SAttributeAccessError_rst;
  SAttributeConversionError := SAttributeConversionError_rst;
  SAttributeIsNotItem := SAttributeIsNotItem_rst;
  SAttributeIsNotValue := SAttributeIsNotValue_rst;
  SAttributeNotFound := SAttributeNotFound_rst;
  SAttributeTypeNotFound := SAttributeTypeNotFound_rst;
  SCannotRecursivelyCreateMetadatas := SCannotRecursivelyCreateMetadatas_rst;
  SClassNotFound := SClassNotFound_rst;
  SEnumMetadataNotFound := SEnumMetadataNotFound_rst;
  SEnumOutOfBounds := SEnumOutOfBounds_rst;
  SInstanceAlreadyOwned := SInstanceAlreadyOwned_rst;
  SInstanceNotFound := SInstanceNotFound_rst;
  SInvalidAttributeClass := SInvalidAttributeClass_rst;
  SInvalidAttributeValue := SInvalidAttributeValue_rst;
  SInvalidClassInheritance := SInvalidClassInheritance_rst;
  SMetadataNotFound := SMetadataNotFound_rst;
  SMetadataParseError := SMetadataParseError_rst;
  SNoReferenceOrDataAccess := SNoReferenceOrDataAccess_rst;
  SPathReferencesNil := SPathReferencesNil_rst;
  SSingletonClassNotFound := SSingletonClassNotFound_rst;
  SStringOverflow := SStringOverflow_rst;
  SUnsupportedAttribute := SUnsupportedAttribute_rst;
  SUnsupportedAttributeType := SUnsupportedAttributeType_rst;
  SUnsupportedGraphicFormat := SUnsupportedGraphicFormat_rst;

  // Error messages from the MVP framework
  SAmbiguousClass := SAmbiguousClass_rst;
  SColumnDataParseError := SColumnDataParseError_rst;
  SComponentIsNotAControl := SComponentIsNotAControl_rst;
  SComponentNotFound := SComponentNotFound_rst;
  SDisplayNamesAlreadyAssigned := SDisplayNamesAlreadyAssigned_rst;
  SMaxItemCountReached := SMaxItemCountReached_rst;
  SUnassignedAttributeType := SUnassignedAttributeType_rst;
  SUnassignedItemObjectClass := SUnassignedItemObjectClass_rst;
  SUnassignedMainForm := SUnassignedMainForm_rst;
  SUnassignedModel := SUnassignedModel_rst;
  SUnassignedPresenterForm := SUnassignedPresenterForm_rst;
  SUnassignedPresenterParent := SUnassignedPresenterParent_rst;
  SUnassignedSubject := SUnassignedSubject_rst;
  SUnexpectedMVPClassParam := SUnexpectedMVPClassParam_rst;
  SUnsupportedComponent := SUnsupportedComponent_rst;
  SUnsupportedControl := SUnsupportedControl_rst;
  SUnsupportedDisplayNames := SUnsupportedDisplayNames_rst;
  SUnsupportedModel := SUnsupportedModel_rst;
  SUnsupportedObject := SUnsupportedObject_rst;
  SViewAccessError := SViewAccessError_rst;

  // Error messages from the OPF framework
  SAttributeReferencesOwnedClass := SAttributeReferencesOwnedClass_rst;
  SCannotChangeOPFBroker := SCannotChangeOPFBroker_rst;
  SCannotStoreOrphanObject := SCannotStoreOrphanObject_rst;
  SCannotUseAggregateFunctionHere := SCannotUseAggregateFunctionHere_rst;
  SClassIsNotPersistent := SClassIsNotPersistent_rst;
  SDatabaseIdentifierTooLong := SDatabaseIdentifierTooLong_rst;
  SFieldNotFound := SFieldNotFound_rst;
  SObjectChangedError := SObjectChangedError_rst;
  STargetClassIsNotPersistent := STargetClassIsNotPersistent_rst;
  SUnassignedPersistenceService := SUnassignedPersistenceService_rst;
  SUnsupportedConnector := SUnsupportedConnector_rst;
  SUnsupportedFieldType := SUnsupportedFieldType_rst;

  // Error messages from brokers
  SUnassignedPersistenceConnector := SUnassignedPersistenceConnector_rst;

  // Messages for visual components
  SConnectionManagerCaption := SConnectionManagerCaption_rst;

  // Messages for Commands
  SPressTodayCommand := SPressTodayCommand_rst;
  SPressLoadPictureCommand := SPressLoadPictureCommand_rst;
  SPressRemovePictureCommand := SPressRemovePictureCommand_rst;
  SPressIncludeObjectCommand := SPressIncludeObjectCommand_rst;
  SPressAddItemCommand := SPressAddItemCommand_rst;
  SPressSelectItemCommand := SPressSelectItemCommand_rst;
  SPressEditItemCommand := SPressEditItemCommand_rst;
  SPressRemoveItemCommand := SPressRemoveItemCommand_rst;
  SPressRefreshCommand := SPressRefreshCommand_rst;
  SPressSaveFormCommand := SPressSaveFormCommand_rst;
  SPressCancelFormCommand := SPressCancelFormCommand_rst;
  SPressCloseFormCommand := SPressCloseFormCommand_rst;
  SPressExecuteQueryCommand := SPressExecuteQueryCommand_rst;
  SPressAssignSelectionQueryCommand := SPressAssignSelectionQueryCommand_rst;
  SPressSelectAllCommand := SPressSelectAllCommand_rst;
  SPressSelectNoneCommand := SPressSelectNoneCommand_rst;
  SPressSelectCurrentCommand := SPressSelectCurrentCommand_rst;
  SPressSelectInvertCommand := SPressSelectInvertCommand_rst;
  SPressSortByCommand := SPressSortByCommand_rst;
  SPressManageReportCommand := SPressManageReportCommand_rst;

  // Partial translations for parsers or another error messages
  SPressAttributeNameMsg := SPressAttributeNameMsg_rst;
  SPressBooleanValueMsg := SPressBooleanValueMsg_rst;
  SPressClassNameMsg := SPressClassNameMsg_rst;
  SPressExpressionMsg := SPressExpressionMsg_rst;
  SPressEofMsg := SPressEofMsg_rst;
  SPressFunctionMsg := SPressFunctionMsg_rst;
  SPressIdentifierMsg := SPressIdentifierMsg_rst;
  SPressIntegerValueMsg := SPressIntegerValueMsg_rst;
  SPressLineBreakMsg := SPressLineBreakMsg_rst;
  SPressNumberValueMsg := SPressNumberValueMsg_rst;
  SPressPropertyNameMsg := SPressPropertyNameMsg_rst;
  SPressReportErrorMsg := SPressReportErrorMsg_rst;
  SPressStringDelimiterMsg := SPressStringDelimiterMsg_rst;
  SPressStringValueMsg := SPressStringValueMsg_rst;

  // Messages for dialog box
  SPressCancelChangesDialog := SPressCancelChangesDialog_rst;
  SPressConfirmRemoveOneItemDialog := SPressConfirmRemoveOneItemDialog_rst;
  SPressConfirmRemoveItemsDialog := SPressConfirmRemoveItemsDialog_rst;
  SPressSaveChangesDialog := SPressSaveChangesDialog_rst;
