  // Error messages from core and adjacent classes
  SCannotReleaseInstance := PressEncodeString(SCannotReleaseInstance_rst);
  SEnumItemNotFound := PressEncodeString(SEnumItemNotFound_rst);
  SInvalidIdentifier := PressEncodeString(SInvalidIdentifier_rst);
  SInvalidInterfaceTypecast := PressEncodeString(SInvalidInterfaceTypecast_rst);
  SInvalidLogon := PressEncodeString(SInvalidLogon_rst);
  SMethodNotFound := PressEncodeString(SMethodNotFound_rst);
  SNoLoggedUser := PressEncodeString(SNoLoggedUser_rst);
  SPasswordsDontMatch := PressEncodeString(SPasswordsDontMatch_rst);
  SPropertyIsReadOnly := PressEncodeString(SPropertyIsReadOnly_rst);
  SPropertyNotFound := PressEncodeString(SPropertyNotFound_rst);
  SServiceNotFound := PressEncodeString(SServiceNotFound_rst);
  SStringLengthOutOfBounds := PressEncodeString(SStringLengthOutOfBounds_rst);
  STokenExpected := PressEncodeString(STokenExpected_rst);
  STokenLengthOutOfBounds := PressEncodeString(STokenLengthOutOfBounds_rst);
  SUnassignedAppManager := PressEncodeString(SUnassignedAppManager_rst);
  SUnassignedServiceType := PressEncodeString(SUnassignedServiceType_rst);
  SUnexpectedEof := PressEncodeString(SUnexpectedEof_rst);
  SUnsupportedFeature := PressEncodeString(SUnsupportedFeature_rst);
  SUnsupportedVariantType := PressEncodeString(SUnsupportedVariantType_rst);

  // Error messages from the Data Type (Subject) framework
  SAttributeAccessError := PressEncodeString(SAttributeAccessError_rst);
  SAttributeConversionError := PressEncodeString(SAttributeConversionError_rst);
  SAttributeIsNotItem := PressEncodeString(SAttributeIsNotItem_rst);
  SAttributeIsNotValue := PressEncodeString(SAttributeIsNotValue_rst);
  SAttributeNotFound := PressEncodeString(SAttributeNotFound_rst);
  SAttributeTypeNotFound := PressEncodeString(SAttributeTypeNotFound_rst);
  SCannotAssignOwnerPartsMetadata := PressEncodeString(SCannotAssignOwnerPartsMetadata_rst);
  SCannotRecursivelyCreateMetadatas := PressEncodeString(SCannotRecursivelyCreateMetadatas_rst);
  SClassNotFound := PressEncodeString(SClassNotFound_rst);
  SEnumMetadataNotFound := PressEncodeString(SEnumMetadataNotFound_rst);
  SEnumOutOfBounds := PressEncodeString(SEnumOutOfBounds_rst);
  SInstanceAlreadyOwned := PressEncodeString(SInstanceAlreadyOwned_rst);
  SInstanceNotFound := PressEncodeString(SInstanceNotFound_rst);
  SInvalidAttributeClass := PressEncodeString(SInvalidAttributeClass_rst);
  SInvalidAttributeName := PressEncodeString(SInvalidAttributeName_rst);
  SInvalidAttributeValue := PressEncodeString(SInvalidAttributeValue_rst);
  SInvalidClassInheritance := PressEncodeString(SInvalidClassInheritance_rst);
  SMetadataNotFound := PressEncodeString(SMetadataNotFound_rst);
  SMetadataParseError := PressEncodeString(SMetadataParseError_rst);
  SNoReferenceOrDataAccess := PressEncodeString(SNoReferenceOrDataAccess_rst);
  SParseFormulaError := PressEncodeString(SParseFormulaError_rst);
  SPathReferencesNil := PressEncodeString(SPathReferencesNil_rst);
  SSingletonClassNotFound := PressEncodeString(SSingletonClassNotFound_rst);
  SStringOverflow := PressEncodeString(SStringOverflow_rst);
  SUnsupportedAttribute := PressEncodeString(SUnsupportedAttribute_rst);
  SUnsupportedAttributeType := PressEncodeString(SUnsupportedAttributeType_rst);
  SUnsupportedGraphicFormat := PressEncodeString(SUnsupportedGraphicFormat_rst);

  // Error messages from the MVP framework
  SAmbiguousClass := PressEncodeString(SAmbiguousClass_rst);
  SColumnDataParseError := PressEncodeString(SColumnDataParseError_rst);
  SComponentIsNotAControl := PressEncodeString(SComponentIsNotAControl_rst);
  SComponentNotFound := PressEncodeString(SComponentNotFound_rst);
  SDisplayNamesAlreadyAssigned := PressEncodeString(SDisplayNamesAlreadyAssigned_rst);
  SMaxItemCountReached := PressEncodeString(SMaxItemCountReached_rst);
  SUnassignedAttributeType := PressEncodeString(SUnassignedAttributeType_rst);
  SUnassignedItemObjectClass := PressEncodeString(SUnassignedItemObjectClass_rst);
  SUnassignedMainForm := PressEncodeString(SUnassignedMainForm_rst);
  SUnassignedModel := PressEncodeString(SUnassignedModel_rst);
  SUnassignedPresenterBO := PressEncodeString(SUnassignedPresenterBO_rst);
  SUnassignedPresenterForm := PressEncodeString(SUnassignedPresenterForm_rst);
  SUnassignedPresenterParent := PressEncodeString(SUnassignedPresenterParent_rst);
  SUnassignedSubject := PressEncodeString(SUnassignedSubject_rst);
  SUnassignedWidgetManager := PressEncodeString(SUnassignedWidgetManager_rst);
  SUnexpectedMVPClassParam := PressEncodeString(SUnexpectedMVPClassParam_rst);
  SUnsupportedComponent := PressEncodeString(SUnsupportedComponent_rst);
  SUnsupportedControl := PressEncodeString(SUnsupportedControl_rst);
  SUnsupportedDisplayNames := PressEncodeString(SUnsupportedDisplayNames_rst);
  SUnsupportedModel := PressEncodeString(SUnsupportedModel_rst);
  SUnsupportedObject := PressEncodeString(SUnsupportedObject_rst);
  SUnsupportedSubject := PressEncodeString(SUnsupportedSubject_rst);
  SViewAccessError := PressEncodeString(SViewAccessError_rst);
  SWidgetManagerAlreadyAssigned := PressEncodeString(SWidgetManagerAlreadyAssigned_rst);

  // Error messages from the OPF framework
  SAttributeCannotBeNull := PressEncodeString(SAttributeCannotBeNull_rst);
  SAttributeReferencesOwnedClass := PressEncodeString(SAttributeReferencesOwnedClass_rst);
  SCannotChangeOPFBroker := PressEncodeString(SCannotChangeOPFBroker_rst);
  SCannotStoreOrphanObject := PressEncodeString(SCannotStoreOrphanObject_rst);
  SCannotUseAggregateFunctionHere := PressEncodeString(SCannotUseAggregateFunctionHere_rst);
  SClassIsNotPersistent := PressEncodeString(SClassIsNotPersistent_rst);
  SDatabaseIdentifierTooLong := PressEncodeString(SDatabaseIdentifierTooLong_rst);
  SFieldNotFound := PressEncodeString(SFieldNotFound_rst);
  SObjectChangedError := PressEncodeString(SObjectChangedError_rst);
  STargetClassIsNotPersistent := PressEncodeString(STargetClassIsNotPersistent_rst);
  SUnassignedPersistenceService := PressEncodeString(SUnassignedPersistenceService_rst);
  SUnsupportedConnector := PressEncodeString(SUnsupportedConnector_rst);
  SUnsupportedFieldType := PressEncodeString(SUnsupportedFieldType_rst);

  // Error messages from brokers
  SUnassignedPersistenceConnector := PressEncodeString(SUnassignedPersistenceConnector_rst);

  // Messages for visual components
  SConnectionManagerCaption := PressEncodeString(SConnectionManagerCaption_rst);

  // Messages for Commands
  SPressTodayCommand := PressEncodeString(SPressTodayCommand_rst);
  SPressLoadPictureCommand := PressEncodeString(SPressLoadPictureCommand_rst);
  SPressRemovePictureCommand := PressEncodeString(SPressRemovePictureCommand_rst);
  SPressIncludeObjectCommand := PressEncodeString(SPressIncludeObjectCommand_rst);
  SPressAddItemCommand := PressEncodeString(SPressAddItemCommand_rst);
  SPressInsertItemCommand := PressEncodeString(SPressInsertItemCommand_rst);
  SPressSelectItemCommand := PressEncodeString(SPressSelectItemCommand_rst);
  SPressEditItemCommand := PressEncodeString(SPressEditItemCommand_rst);
  SPressRemoveItemCommand := PressEncodeString(SPressRemoveItemCommand_rst);
  SPressRefreshCommand := PressEncodeString(SPressRefreshCommand_rst);
  SPressSaveFormCommand := PressEncodeString(SPressSaveFormCommand_rst);
  SPressCancelFormCommand := PressEncodeString(SPressCancelFormCommand_rst);
  SPressCloseFormCommand := PressEncodeString(SPressCloseFormCommand_rst);
  SPressExecuteQueryCommand := PressEncodeString(SPressExecuteQueryCommand_rst);
  SPressAssignSelectionQueryCommand := PressEncodeString(SPressAssignSelectionQueryCommand_rst);
  SPressSelectAllCommand := PressEncodeString(SPressSelectAllCommand_rst);
  SPressSelectNoneCommand := PressEncodeString(SPressSelectNoneCommand_rst);
  SPressSelectCurrentCommand := PressEncodeString(SPressSelectCurrentCommand_rst);
  SPressSelectInvertCommand := PressEncodeString(SPressSelectInvertCommand_rst);
  SPressSortByCommand := PressEncodeString(SPressSortByCommand_rst);
  SPressManageReportCommand := PressEncodeString(SPressManageReportCommand_rst);

  // Partial translations for parsers or another error messages
  SPressAttributeNameMsg := PressEncodeString(SPressAttributeNameMsg_rst);
  SPressBooleanValueMsg := PressEncodeString(SPressBooleanValueMsg_rst);
  SPressClassNameMsg := PressEncodeString(SPressClassNameMsg_rst);
  SPressExpressionMsg := PressEncodeString(SPressExpressionMsg_rst);
  SPressEofMsg := PressEncodeString(SPressEofMsg_rst);
  SPressFunctionMsg := PressEncodeString(SPressFunctionMsg_rst);
  SPressIdentifierMsg := PressEncodeString(SPressIdentifierMsg_rst);
  SPressIntegerValueMsg := PressEncodeString(SPressIntegerValueMsg_rst);
  SPressLineBreakMsg := PressEncodeString(SPressLineBreakMsg_rst);
  SPressNumberValueMsg := PressEncodeString(SPressNumberValueMsg_rst);
  SPressPropertyNameMsg := PressEncodeString(SPressPropertyNameMsg_rst);
  SPressReportErrorMsg := PressEncodeString(SPressReportErrorMsg_rst);
  SPressStringDelimiterMsg := PressEncodeString(SPressStringDelimiterMsg_rst);
  SPressStringValueMsg := PressEncodeString(SPressStringValueMsg_rst);

  // Messages for user access
  SPressNoAccess := PressEncodeString(SPressNoAccess_rst);
  SPressReadOnlyAccess := PressEncodeString(SPressReadOnlyAccess_rst);
  SPressReadWriteAccess := PressEncodeString(SPressReadWriteAccess_rst);

  // Messages for dialog box
  SPressCancelChangesDialog := PressEncodeString(SPressCancelChangesDialog_rst);
  SPressConfirmRemoveOneItemDialog := PressEncodeString(SPressConfirmRemoveOneItemDialog_rst);
  SPressConfirmRemoveItemsDialog := PressEncodeString(SPressConfirmRemoveItemsDialog_rst);
  SPressSaveChangesDialog := PressEncodeString(SPressSaveChangesDialog_rst);
