  // Error messages from core and adjacent classes
  SCannotReleaseInstance_rst = 'Instanz ''%s'' kann nicht freigegeben werden.';
  SEnumItemNotFound_rst = 'Aufzählung ''%s'' nicht gefunden';
  SInvalidIdentifier_rst = 'Ungültiger Bezeichner ''%s''';
  SInvalidInterfaceTypecast_rst = 'Ungültiger interface typecast';
  SInvalidLogon_rst = 'Ungültiger Benutzername oder Kennwort';
  SMethodNotFound_rst = 'Methode ''%s'' nicht gefunden';
  SNoLoggedUser_rst = 'Kein Benutzer angemeldet';
  SPasswordsDontMatch_rst = 'Kennwörter stimmen nicht überein';
  SPropertyIsReadOnly_rst = 'Die Eigenschaft ''%s.%s'' ist nur-Lesen';
  SPropertyNotFound_rst = 'Eigenschaft ''%s.%s'' nicht gefunden';
  SServiceNotFound_rst = 'Service ''%s'' nicht gefunden';
  SStringLengthOutOfBounds_rst = 'String zu lang';
  STokenExpected_rst = '''%s'' erwartet, aber ''%s'' gefunden';
  STokenLengthOutOfBounds_rst = 'Token zu lang';
  SUnassignedAppManager_rst = 'Anwendungsmanager nicht zugewiesen';
  SUnassignedServiceType_rst = 'Es ist kein Service ''%s'' zugewiesen oder registriert';
  SUnexpectedEof_rst = 'Unerwartetes Dateiende';
  SUnsupportedFeature_rst = 'Feature ''%s'' nicht unterstützt';
  SUnsupportedVariantType_rst = 'Nicht unterstützter Varianttyp';

  // Error messages from the Data Type (Subject) framework
  SAttributeAccessError_rst = 'Auf das Attribut %s(''%s'') kann nicht als ''%s'' zugegriffen werden';
  SAttributeConversionError_rst = 'Fehler bei der Umwandlung des Attributs %s(''%s''):' + SPressLineBreak + '"%s"';
  SAttributeIsNotItem_rst = 'Attribut %s(''%s'') ist weder Part noch Reference';
  SAttributeIsNotValue_rst = 'Attribut %s(''%s'') ist kein Wert';
  SAttributeNotFound_rst = 'Attribut %s(''%s'') nicht gefunden';
  SAttributeTypeNotFound_rst = 'Attribut ''%s'' nicht gefunden';
  SCannotRecursivelyCreateMetadatas_rst = 'Metadata kann nicht rekursiv erstellt werden';
  SClassNotFound_rst = 'Klasse ''%s'' nicht gefunden';
  SEnumMetadataNotFound_rst = 'Aufzählungs-Metadata ''%s'' nicht gefunden';
  SEnumOutOfBounds_rst = 'Aufzählung ''%s'' nicht im Bereich (%d)';
  SInstanceAlreadyOwned_rst = 'Die Instanz %s(''%s'') hat schon einen Owner';
  SInstanceNotFound_rst = 'Instanz nicht gefunden: %s(''%s'')';
  SInvalidAttributeClass_rst = 'Attribut %s(''%s'') benötigt Objekte der Klasse ''%s''';
  SInvalidAttributeName_rst = 'Ungültiger Attributname (''%s'')';
  SInvalidAttributeValue_rst = 'Wert ''%s'' ist kein gültiger Wert für %s(''%s'')';
  SInvalidClassInheritance_rst = 'Klasse ''%s'' ist kein Nachfahre von ''%s''';
  SMetadataNotFound_rst = 'Metadata ''%s'' nicht gefunden';
  SMetadataParseError_rst = 'Metadata parse error: "(%d,%d) %s"' + SPressLineBreak + '"%s"';
  SNoReferenceOrDataAccess_rst = 'Reference oder DAO nicht vorhanden';
  SParseFormulaError_rst = 'Fehler beim Parsen der Formel:' + SPressLineBreak + '%s' + SPressLineBreak + '%s';
  SPathReferencesNil_rst = 'Der Pfad %s(''%s'') hat Attribut(e) mit null-Referenze(n)';
  SSingletonClassNotFound_rst = 'Singleton Klasse ''%s'' nicht gefunden';
  SStringOverflow_rst = 'String Überlauf: %s(''%s'')';
  SUnsupportedAttribute_rst = 'Nicht unterstütztes Attribut %s(''%s'')';
  SUnsupportedAttributeType_rst = 'Nicht unterstütztes Attribut Typ ''%s''';
  SUnsupportedGraphicFormat_rst = 'Nicht unterstütztes Graphikformat';

  // Error messages from the MVP framework
  SAmbiguousClass_rst = 'Auswahl zwischen den Klassen ''%s'' und ''%s'' nicht eindeutig';
  SColumnDataParseError_rst = 'Fehler beim parsen der Spaltendaten %s(''%s''): "%s"';
  SComponentIsNotAControl_rst = 'Component %s(''%s'') ist kein Control';
  SComponentNotFound_rst = 'Component %s(''%s'') nicht gefunden';
  SDisplayNamesAlreadyAssigned_rst = 'Anzeigenamen sind schon zugewiesen';
  SMaxItemCountReached_rst = '%d items wurden zurückgegeben, das Limit ist %d';
  SUnassignedAttributeType_rst = 'Nicht zugewiesener Attributtyp %s(''%s'')';
  SUnassignedItemObjectClass_rst = 'Nicht zugewiesene business Klasse Query item ''%s''';
  SUnassignedMainForm_rst = 'Hauptformular nicht zugewiesen';
  SUnassignedModel_rst = 'Model nicht zugewiesenen';
  SUnassignedPresenterForm_rst = 'Klasse ''%s'' hat kein Formular';
  SUnassignedPresenterParent_rst = 'Klasse ''%s'' hat kein Parent';
  SUnassignedSubject_rst = 'Nicht zugewiesenes Subjekt';
  SUnassignedWidgetManager_rst = 'Nicht zugewiesener Widgetmanager';
  SUnexpectedMVPClassParam_rst = 'MVP Klasse ''%s'' hat unewartete Parameter';
  SUnsupportedComponent_rst = 'Nicht unterstützte Komponente ''%s''';
  SUnsupportedControl_rst = 'Nicht unterstütztes Control %s(''%s'')';
  SUnsupportedDisplayNames_rst = 'Nicht unterstützte Anzeigenamen für Attribut %s(''%s.%s'')';
  SUnsupportedModel_rst = 'Model %s  wird von ''%s'' nicht unterstützt';
  SUnsupportedObject_rst = 'Keine Klasse %s unterstützt Objekte ''%s''';
  SViewAccessError_rst = 'Kann nicht auf die View %s(''%s'') als ''%s'' zugreifen';
  SWidgetManagerAlreadyAssigned_rst = 'Widgetmanager bereits zugewiesen';

  // Error messages from the OPF framework
  SAttributeReferencesOwnedClass_rst = '%s(%s) referenziert ''%s'' welches zu ''%s'' gehört';
  SCannotChangeOPFBroker_rst = 'Kann den Databroker nicht ändern';
  SCannotStoreOrphanObject_rst = 'Kann orphan object nicht speichern';
  SCannotUseAggregateFunctionHere_rst = 'Aggregatfunktion kann hier nicht angewendet werden';
  SClassIsNotPersistent_rst = 'Klasse ''%s'' ist nicht persistent';
  SDatabaseIdentifierTooLong_rst = 'Der Bezeichner ' + SPressLineBreak + ' ist zu lang und verursacht einen Fehler in der Datenbank:';
  SFieldNotFound_rst = 'Feld ''%s'' nicht gefunden';
  SObjectChangedError_rst = 'Das Objekt %s(''%s'') wurde in einer anderen Session bereits geändert';
  STargetClassIsNotPersistent_rst = '%s(%s) referenziert ''%s'' welches nicht persistent ist';
  SUnassignedPersistenceService_rst = 'Nicht zugewiesener oderr nicht-PressObjects Persistenz-Service';
  SUnsupportedConnector_rst = 'Nicht unterstützter Connector ''%s''';
  SUnsupportedFieldType_rst = 'Nicht unterstützte Feldtyp ''%s''';

  // Error messages from brokers
  SUnassignedPersistenceConnector_rst = 'Nicht zugewiesener Persistenz-Connector';

  // Messages for visual components
  SConnectionManagerCaption_rst = 'Connector';

  // Messages for Commands
  SPressTodayCommand_rst = 'Heute';
  SPressLoadPictureCommand_rst = 'Bild laden';
  SPressRemovePictureCommand_rst = 'Bild entfernen';
  SPressIncludeObjectCommand_rst = 'Neuer Eintrag';
  SPressAddItemCommand_rst = 'Neuer Eintrag';
  SPressSelectItemCommand_rst = 'Einträge auswählen';
  SPressEditItemCommand_rst = 'Eintrag bearbeiten';
  SPressRemoveItemCommand_rst = 'Eintrag löschen';
  SPressRefreshCommand_rst = 'aktualisieren';
  SPressSaveFormCommand_rst = 'Speichern';
  SPressCancelFormCommand_rst = 'Abbrechen';
  SPressCloseFormCommand_rst = 'Schliessen';
  SPressExecuteQueryCommand_rst = 'Ausführen';
  SPressAssignSelectionQueryCommand_rst = 'Filter';
  SPressSelectAllCommand_rst = 'Alles markieren';
  SPressSelectNoneCommand_rst = 'Markierung aufheben';
  SPressSelectCurrentCommand_rst = 'Markierung umschalten';
  SPressSelectInvertCommand_rst = 'Markierung umkehren';
  SPressSortByCommand_rst = 'Sortieren nach ''%s''';
  SPressManageReportCommand_rst = 'Bericht verwalten';

  // Partial translations for parsers or another error messages
  SPressAttributeNameMsg_rst = 'Attributname';
  SPressBooleanValueMsg_rst = 'Boolean Ausdruck';
  SPressClassNameMsg_rst = 'Klassenname';
  SPressExpressionMsg_rst = 'Ausdruck';
  SPressEofMsg_rst = 'Dateiende';
  SPressFunctionMsg_rst = 'Funktion';
  SPressIdentifierMsg_rst = 'Bezeichner';
  SPressIntegerValueMsg_rst = 'Integer';
  SPressLineBreakMsg_rst = 'Zeilenumbruch';
  SPressNumberValueMsg_rst = 'Nummer';
  SPressPropertyNameMsg_rst = 'Eigenschaftsname';
  SPressReportErrorMsg_rst = ' ##Fehler## ';
  SPressStringDelimiterMsg_rst = 'Trennzeichen';
  SPressStringValueMsg_rst = 'String';

  // Messages for user access
  { TODO : Translate }
  SPressNoAccess_rst = 'No access';
  SPressReadOnlyAccess_rst = 'Read-only access';
  SPressReadWriteAccess_rst = 'Full access';

  // Messages for dialog box
  SPressCancelChangesDialog_rst = 'Änderungen verwerfen?';
  SPressConfirmRemoveOneItemDialog_rst = 'Gewählten Eintrag löschen?';
  SPressConfirmRemoveItemsDialog_rst = '%d Einträge ausgewählt. Löschen?';
  SPressSaveChangesDialog_rst = 'Änderungen speichern?';
